import Head from 'next/head'

const HTMLHeader = () => {
    return (
        <Head>
            <title>WOB MUSIC GROUP</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
        </Head>
    )
}

export default HTMLHeader;